### ISSUE TITLE
Error during checkout

### ISSUE THREAD

**Issue by arakhia** [aserg-ufmg/apidiff#7]
Hello @alinebrito ,

I'm facing an issue when trying to use the example provided in the ReadME file.

`APIDiff diff = new APIDiff("bumptech/glide", "https://github.com/bumptech/glide.git");
diff.setPath("/home/projects/github");
Result result = diff.detectChangeAllHistory("master", Classifier.API);
for(Change changeMethod : result.getChangeMethod()){
    System.out.println("\n" + changeMethod.getCategory().getDisplayName() + " - " + changeMethod.getDescription());
}`

I get a lot of same response as below

`20:09:54.832 [main] ERROR apidiff.APIDiff - Error during checkout [commit=commit 32f25e61f2e3deaf82a09ddb5abc0dcebacf4ff8 1449096449 ----sp]
20:09:54.833 [main] ERROR apidiff.APIDiff - Error during checkout [commit=commit 2ab0e01abe1fd7b31863b8dcbb753677d5c08cbf 1449096449 ----sp]
20:09:54.834 [main] ERROR apidiff.APIDiff - Error during checkout [commit=commit dbeedd0e526de8c896e9415ff61aded736162b12 1448541302 ----sp]
20:09:54.836 [main] ERROR apidiff.APIDiff - Error during checkout [commit=commit 958673285748732dc2b69650e28491640fdefe60 1448463880 ----sp]
20:09:54.837 [main] ERROR apidiff.APIDiff - Error during checkout [commit=commit aa751f6289ea16ef35955f7563038c6c51c6a4e2 1448402552 ----sp]
20:09:54.839 [main] ERROR apidiff.APIDiff - Error during checkout [commit=commit 9054725ba29c0fc9960a7334cedc74922893b8a5 1448390197 ----sp]
20:09:54.840 [main] ERROR apidiff.APIDiff - Error during checkout [commit=commit 4bf613932737fabc2f951e508215eae1f4487a5a 1448387180 ----sp]
20:09:54.842 [main] ERROR apidiff.APIDiff - Error during checkout [commit=commit ab277ca637be436afb1ae75628a0af0e1e607ab5 1448387174 ----sp]`
I tried other examples and got same error.
Can you please help me?

Thank you

**Comment by arakhia** [comment]
Thanks for the amazing tool @alinebrito 

I did remove the local folder bumptech/glide inside /guthub, and then after running the tool it pulled the project from Github Website into my local folder, but also I got the same message "Error during checkout ".

I may misunderstood the usage of the tool. Can you please explain to me the following scenario. For example, if I want to detect breaking changes between glide 
**glide Version 4.12.0 (Recent)**: https://github.com/bumptech/glide/tree/v4.12.0
and 
**glide Version 4.8.0**: https://github.com/bumptech/glide/tree/v4.8.0

Which one should be in my local folder and which one should I inject as a parameter in the `new APIDiff()` Class?
How to write the code to perform this example

**Comment by arakhia** [comment]
Hi @alinebrito 

Sorry for any inconvenience, can you please check my reply, I really need your tool for my research.

**Comment by alinebrito** [comment]
Hi @arakhia 

Sorry for the late reply. Feel free to contact me!

Could you put the code you are trying to run here, please?

``Can you please explain to me the following scenario.``
In this version, there is no option to compare changes between two branches/releases. We can detect all changes performed in a single branch. APIDiff lists all commits from a branch. Then, it uses an iterator to compare each commit with its parent.

``Which one should be in my local folder and which one should I inject as a parameter in the new APIDiff() Class?``
The local folder contains all history of the project (i.e., ``git clone --bare``).

**Comment by arakhia** [comment]
Hi @alinebrito  thanks for your reply,

I need to find breaking changes between two git branches or jar files. If you are aware of any tool that would be helpful.

Thanks for the support, I will close this issue.
